#!/usr/bin/env bash

PASSRC=${PASSRC:-"$HOME/.passrc"}
PASS_STORE=${PASS_STORE:-"$HOME/.pass/"}

PASSWORD_STORE="$PASS_STORE/passwords/"
OTP_STORE="$PASS_STORE/otp/"
RECUVA_STORE="$PASS_STORE/recovery/"

ENTROPY_SALT=$(sed -n 's/^ENTROPY_SALT=//p' "$PASSRC")
ENTROPY_ITERATION=$(sed -n 's/^ENTROPY_ITERATION=//p' "$PASSRC")
ENTROPY_AMPLIFICATION=$(sed -n 's/^ENTROPY_AMPLIFICATION=//p' "$PASSRC")

switch_mode="Ctrl+s"
addpass="Alt+a"
delete="Ctrl-x"
close="Ctrl-z"
close_tomb="Ctrl-Z"
open_tomb="Ctrl-o"
edit="Ctrl-y"
recuva_mode="Ctrl-r"

help_color="#7c5cff"
div_color="#334433"
label="#f067fc"

if [ ! -d "$PASS_STORE" ]; then
  notify-send -u normal "Pass: Error" "No PASS_STORE found!"
fi

if ls "$PASS_STORE"; then
  for dir in "$PASSWORD_STORE" "$OTP_STORE" "$RECUVA_STORE"; do
    if [ ! -d "$dir" ]; then
      mkdir -p "$dir"
    fi
  done
fi

if ! command -v rofi &>/dev/null; then
  echo "rofi could not be found. Please install it."
  exit 1
fi

function usage() {
  cat <<EOF
pass-rofi: A rofi extension for pass

Usage: $0 [options] <command> [arguments]

Options:
  -e             Exhume buried key to unlock a tomb
  -k [-e -g]     Specify a Tomb Key if not present in .passrc
  -g             Create a tomb key using GPG ID
  -h             Display this help message and exit
  -v             Display the current version number

Commands:
  help                     Display this help message and exit
  version                  Display the current version number

Examples:
  pass-rofi -e -g -k tomb.key
                 # Use a GPG key that is buried to unlock a tomb
EOF
}

_rofi() {
  rofi -dmenu -i -no-levenshtein-sort -width 1000 "$@"
}

function version() {
  echo "v.1.1.0"
}

function error() {
  notify-send -u normal "Pass: Error" "An unknown error occurred!"
}

function tomb_open() {
  TOMB_KEY=${TOMB_KEY:-$(sed -n 's/^TOMB_KEY=//p' "$PASSRC")}
  if [ "$EXHUME" = "true" ] && [ "$GPG_ID" = "true" ]; then
    pass-tomb -e -g open "$TOMB_KEY"
  elif [ "$EXHUME" = "true" ]; then
    pass-tomb -e open "$TOMB_KEY"
  elif [ "$GPG_ID" = "true" ]; then
    pass-tomb -g open "$TOMB_KEY"
  else
    pass-tomb open "$TOMB_KEY"
  fi
}

function deleteMenu() {
  delask=$(echo -e "1. Yes\n2. No" | _rofi -p '> ' -mesg "<span color='${label}'>Really delete</span> <span color='${help_color}'>$menu?</span>")
  val=$?
  if [[ $val -eq 1 ]]; then
    notify-send -u low "Pass: Delete" "Cancelled!"
    mode=pass main
  fi
  if [[ "$delask" == "1. Yes" ]]; then
    case "$mode" in
    pass)
      pass -n -f rm "$menu" || error
      ;;
    otp)
      pass-otp -n -f rm "$menu" || error
      ;;
    recuva)
      rm "$menu" || error
      git -C "$passdir" add "$menu" &&
        git -C "$passdir" commit "$menu" -m "Delete recovery key $menu"
      ;;
    esac
  fi
  mode=pass main
}

function addMenu() {
  addmenu=$(echo | _rofi -p '> ' -mesg "<span color='${label}'>Usage: </span>Insert directory/passname")
  val=$?
  if [[ $val -eq 1 ]]; then
    notify-send -u low "Pass: Add" "Cancelled!"
    mode=pass main
  elif [[ $val -eq 0 ]]; then
    case "$mode" in
    pass)
      pass -n -d zenity generate "$addmenu" 72 || error
      ;;
    otp)
      otp_key=$(zenity --entry --title="Enter OTP Key" --text="Please enter your OTP Key. No spaces allowed:")
      pass-otp -n -d zenity generate "$addmenu" "$otp_key" || error
      ;;
    recuva)
      if [ "$ENTROPY_AMPLIFICATION" = "true" ]; then
        pass-otp -n -a -s "$ENTROPY_SALT" -i "$ENTROPY_ITERATION" recuva "$addmenu"
      else
        pass-otp -n recuva "$addmenu"
      fi
      ;;
    esac
  fi
  mode=pass main
}

function editMenu() {
  term=${TERMCMD:-kitty}
  case "$mode" in
  otp)
    if [ "$ENTROPY_AMPLIFICATION" = "true" ]; then
      $term -- sh -c "pass-otp -n -d zenity -a -s $ENTROPY_SALT -i $ENTROPY_ITERATION edit \"$menu\""
    else
      $term -- sh -c "pass-otp -n -d zenity edit \"$menu\""
    fi
    ;;
  recuva)
    if [ "$ENTROPY_AMPLIFICATION" = "true" ]; then
      $term -- sh -c "pass-otp -n -d zenity -a -s $ENTROPY_SALT -i $ENTROPY_ITERATION recuva \"$menu\""
    else
      $term -- sh -c "pass-otp -n -d zenity recuva \"$menu\""
    fi
    ;;
  esac
}

main() {
  case "$mode" in
  pass)
    HELP="<span color='${label}'>Modes: </span><span color='${help_color}'>${switch_mode}</span>: toggle (pass/otp) <span color='${div_color}'>|</span> <span color='${help_color}'>${recuva_mode}</span>: toggle recuva
<span color='${label}'>Close: </span> <span color='${help_color}'>${close}</span>: close key <span color='${div_color}'>|</span> <span color='${help_color}'>${close_tomb}</span>: close tomb <span color='${div_color}'>|</span> <span color='${help_color}'>${open_tomb}</span>: open tomb
<span color='${label}'>Actions: </span> <span color='${help_color}'>${addpass}</span>: Add <span color='${div_color}'>|</span> <span color='${help_color}'>${delete}</span>: Delete"
    passdir="$PASSWORD_STORE"
    ;;
  otp | recuva)
    HELP="<span color='${label}'>Modes: </span><span color='${help_color}'>${switch_mode}</span>: toggle (pass/otp) <span color='${div_color}'>|</span> <span color='${help_color}'>${recuva_mode}</span>: toggle recuva
<span color='${label}'>Close: </span> <span color='${help_color}'>${close}</span>: close key <span color='${div_color}'>|</span> <span color='${help_color}'>${close_tomb}</span>: close tomb
<span color='${label}'>Actions: </span><span color='${help_color}'>${addpass}</span>: Add <span color='${div_color}'>|</span> <span color='${help_color}'>${delete}</span>: Delete <span color='${div_color}'>|</span> <span color='${help_color}'>${edit}</span>: Edit"
    case "$mode" in
    otp)
      passdir="$OTP_STORE"
      ;;
    recuva)
      passdir="$RECUVA_STORE"
      ;;
    esac
    ;;
  esac

  if ! ls "$PASS_STORE"; then
    notify-send -u low "Your Tomb is not opened!" --expire-time=3500
  fi
  pass=$(find "$passdir" -type f -name '*.age' -printf '%P\n' | awk -F. '{print $1}')
  menu=$(echo "${pass}" | _rofi -p "$mode" -mesg "${HELP}" -kb-custom-1 "${addpass}" -kb-custom-2 "${switch_mode}" -kb-custom-3 "${delete}" -kb-custom-4 "${edit}" -kb-custom-5 "${recuva_mode}" -kb-custom-6 "${close}" -kb-custom-7 "${close_tomb}" -kb-custom-8 "${open_tomb}")

  val=$?
  case "$val" in
  1) exit ;;
  12) deleteMenu ;;
  11) # Modes
    case "$mode" in
    otp) mode=pass ;;
    pass) mode=otp ;;
    recuva) mode=pass ;;
    esac
    main
    ;;
  10) addMenu ;;
  13) editMenu ;;
  14)
    mode=recuva
    main
    ;;
  15)
    pass -n close
    ;;
  16)
    tomb slam && notify-send -u normal "Pass: Tomb" "Your tomb is closed"
    ;;
  17)
    TOMB_KEY=${TOMB_KEY:-$(sed -n 's/^TOMB_KEY=//p' "$PASSRC")}
    tomb_open "$TOMB_KEY" && notify-send -u normal "Pass: Tomb" "Your tomb is open"
    main
    ;;
  0)
    case "$mode" in
    pass)
      if [ "$ENTROPY_AMPLIFICATION" = "true" ]; then
        pass -d zenity -n -a -s "$ENTROPY_SALT" -i "$ENTROPY_ITERATION" "$menu"
      else
        pass -d zenity -n cp "$menu"
      fi
      ;;
    otp)
      if [ "$ENTROPY_AMPLIFICATION" = "true" ]; then
        pass-otp -d zenity -n -a -s "$ENTROPY_SALT" -i "$ENTROPY_ITERATION" cp "$menu"
      else
        pass-otp -d zenity -n cp "$menu"
      fi
      ;;
    recuva)
      if [ "$ENTROPY_AMPLIFICATION" = "true" ]; then
        pass-otp -d zenity -n -a -s "$ENTROPY_SALT" -i "$ENTROPY_ITERATION" recuva "$menu"
      else
        pass-otp -d zenity -n recuva "$menu"
      fi
      ;;
    esac
    ;;
  esac
}

while getopts ":hvgek:" opt; do
  case "$opt" in
  h)
    usage
    exit 0
    ;;
  v)
    version
    exit 0
    ;;
  e)
    EXHUME=true
    ;;
  g)
    GPG_DIG=true
    ;;
  k)
    TOMB_KEY="$OPTARG"
    ;;
  ?)
    echo "Error: Invalid option '-$OPTARG'" >&2
    usage
    ;;
  esac
done

shift $((OPTIND - 1))

mode=pass main
